# Generated by Django 2.2.7 on 2019-11-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='data_registration',
        ),
    ]
