# Generated by Django 2.2.7 on 2019-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_purchasing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
